// See Spec-Ingest-Tool.md section 12a (application generator) / 12b
// (enterprise-architecture generator) / 13c-13d (Terraform generator).
//
// Generates a real, runnable repository from a scored corpus + profile:
// a zero-runtime-dependency Node backend (every route is a 501 stub
// naming the candidate that justified it -- this generator can prove a
// route SHOULD exist, never what it should DO), a static no-JS frontend,
// a zero-dependency test suite (node:test), a CI workflow, and a
// Terraform scaffold where every environment-specific value is a
// variable with NO default (account IDs, regions, VPC/subnet IDs,
// CIDRs, IAM principals, and state-backend locations are never
// invented).
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import type { Corpus } from './specMerge.js'
import type { Profile } from './profiles/types.js'
import type { SourceMarking } from './markings.js'

export interface GeneratedFile {
  path: string
  content: string
}

export interface GenerateResult {
  files: GeneratedFile[]
}

export interface GenerateOptions {
  classification?: SourceMarking
}

function classificationBanner(classification: SourceMarking | undefined): string {
  return classification ? `Classification: ${classification}` : 'Classification: UNMARKED'
}

function slugify(text: string): string {
  // The preceding replace collapses every run of non-alphanumeric
  // characters to a single dash, so at most one leading/trailing dash
  // can remain -- trimming a single dash needs no `+` quantifier at all.
  const slug = text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-/, '')
    .replace(/-$/, '')
    .slice(0, 40)
  return slug || 'item'
}

function escapeHtml(text: string): string {
  return text.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;')
}

interface RouteInfo {
  method: string
  path: string
  because: string
}

// Every route candidate becomes a GET /api/<slug> stub -- deduplicated
// by path, since two sources can name the same endpoint.
function buildRoutes(corpus: Corpus): RouteInfo[] {
  const seen = new Set<string>()
  const routes: RouteInfo[] = []
  for (const candidate of corpus.candidates) {
    if (candidate.kind !== 'endpoint' && candidate.kind !== 'record') continue
    const path = `/api/${slugify(candidate.text)}`
    if (seen.has(path)) continue
    seen.add(path)
    routes.push({ method: 'GET', path, because: candidate.because })
  }
  return routes
}

export function generateBackend(corpus: Corpus): GeneratedFile[] {
  const routes = buildRoutes(corpus)
  const routeEntries = routes
    .map((r) => `  '${r.method} ${r.path}': { because: ${JSON.stringify(r.because)} },`)
    .join('\n')

  const content = `#!/usr/bin/env node
// Generated by Spec-Ingest Tool. Zero runtime dependencies -- built on
// node:http only. Every route below is a 501 stub: this generator can
// prove a route SHOULD exist (a source candidate named it) but never
// invents what it should do.
import { createServer } from 'node:http'
import { pathToFileURL } from 'node:url'

export const ROUTES = {
${routeEntries || '  // no endpoint/record candidates were found in the source corpus'}
}

export function requestListener(req, res) {
  const key = \`\${req.method} \${req.url}\`
  const route = ROUTES[key]
  if (route) {
    res.writeHead(501, { 'content-type': 'application/json' })
    res.end(JSON.stringify({ error: 'not implemented', route: key, because: route.because }))
    return
  }
  res.writeHead(404, { 'content-type': 'application/json' })
  res.end(JSON.stringify({ error: 'not found' }))
}

export const server = createServer(requestListener)

const PORT = process.env.PORT ? Number(process.env.PORT) : 3000
if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  server.listen(PORT, () => console.log(\`listening on \${PORT}\`))
}
`
  return [{ path: 'server.mjs', content }]
}

function renderListItem(candidate: { text: string }): string {
  return `<li>${escapeHtml(candidate.text)}</li>`
}

function renderCandidateList(items: { text: string }[]): string {
  if (items.length === 0) return '<p class="empty">No source material yet.</p>'
  return '<ul>' + items.map(renderListItem).join('') + '</ul>'
}

export function generateFrontend(corpus: Corpus, profile: Profile, options: GenerateOptions = {}): GeneratedFile[] {
  const sectionsHtml = profile.sections
    .map((section) => {
      const items = corpus.candidates.filter((c) => section.kinds.includes(c.kind))
      const itemsHtml = renderCandidateList(items)
      return `<section><h2>${escapeHtml(section.title)}</h2>${itemsHtml}</section>`
    })
    .join('\n')

  // No <script>, no on* attribute, no <style> block/attribute -- the
  // theme lives in a linked stylesheet, not inline.
  const indexHtml = `<!doctype html>
<html>
<head>
<meta charset="utf-8">
<link rel="stylesheet" href="theme.css">
<title>${escapeHtml(profile.name)}</title>
</head>
<body>
<p class="classification">${escapeHtml(classificationBanner(options.classification))}</p>
<h1>${escapeHtml(profile.name)}</h1>
<p>${escapeHtml(profile.description)}</p>
${sectionsHtml}
</body>
</html>
`
  const themeCss = `/* Generated by Spec-Ingest Tool -- dark only, no light variant. */
:root { color-scheme: dark; --bg: #0b0d10; --fg: #e6e6e6; --accent: #6ea8fe; }
html, body { background: var(--bg); color: var(--fg); font-family: system-ui, sans-serif; margin: 0; padding: 2rem; }
a { color: var(--accent); }
.classification { font-weight: 700; letter-spacing: 0.08em; text-transform: uppercase; }
`
  return [
    { path: 'public/index.html', content: indexHtml },
    { path: 'public/theme.css', content: themeCss },
  ]
}

export function generateTests(corpus: Corpus): GeneratedFile[] {
  const routes = buildRoutes(corpus)
  const assertions = routes
    .map((r) => {
      const testName = `${r.method} ${r.path} is a declared 501 stub`
      return `test(${JSON.stringify(testName)}, async () => {
  const res = await callRoute('${r.method}', '${r.path}')
  assert.equal(res.statusCode, 501)
})`
    })
    .join('\n\n')

  const content = `// Generated by Spec-Ingest Tool. Uses node:test + node:assert only --
// zero test-framework dependency, matching the generated app's own
// zero-runtime-dependency stance.
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { createServer, request as httpRequest } from 'node:http'
import { requestListener } from '../server.mjs'

function callRoute(method, path) {
  return new Promise((resolve, reject) => {
    const server = createServer(requestListener)
    server.listen(0, () => {
      const { port } = server.address()
      const req = httpRequest({ host: '127.0.0.1', port, path, method }, (res) => {
        res.on('data', () => {})
        res.on('end', () => {
          server.close()
          resolve(res)
        })
      })
      req.on('error', (err) => {
        server.close()
        reject(err)
      })
      req.end()
    })
  })
}

test('unknown route returns 404', async () => {
  const res = await callRoute('GET', '/api/__definitely-not-a-real-route__')
  assert.equal(res.statusCode, 404)
})

${assertions}
`
  return [{ path: 'test/server.test.mjs', content }]
}

export function generateCiWorkflow(): GeneratedFile[] {
  const content = `name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      # Zero dependencies, runtime or dev -- npm install has nothing to
      # fetch, so no committed lockfile is required for this generated app.
      - run: npm install
      - run: node --test
`
  return [{ path: '.github/workflows/ci.yml', content }]
}

export function generateTerraform(profile: Profile): GeneratedFile[] {
  const variablesTf = `# Generated by Spec-Ingest Tool. Every environment-specific value is a
# variable with NO default -- this generator never invents an account
# ID, region, VPC/subnet ID, CIDR, IAM principal, or state-backend
# location (Spec-Ingest-Tool.md security posture, section 13B/2a).

variable "aws_region" {
  type        = string
  description = "AWS region to deploy into."
}

variable "aws_account_id" {
  type        = string
  description = "AWS account ID."
}

variable "vpc_id" {
  type        = string
  description = "VPC ID to deploy into."
}

variable "subnet_ids" {
  type        = list(string)
  description = "Subnet IDs to deploy into."
}

variable "iam_role_arn" {
  type        = string
  description = "IAM role ARN the deployed service assumes."
}

variable "state_bucket" {
  type        = string
  description = "S3 bucket for Terraform remote state (supplied via -backend-config, never hardcoded)."
}
`
  const mainTf = `# Generated scaffold for ${profile.name}. No resource is declared here
# -- this generator has no authority to invent infrastructure shape, only
# to guarantee every environment-specific value stays a variable.
terraform {
  backend "s3" {
    # bucket/key/region are supplied via -backend-config at
    # \`terraform init\` time -- see variables.tf's state_bucket.
  }
}

provider "aws" {
  region = var.aws_region
}
`
  return [
    { path: 'infra/variables.tf', content: variablesTf },
    { path: 'infra/main.tf', content: mainTf },
  ]
}

export function generateApplication(corpus: Corpus, profile: Profile, options: GenerateOptions = {}): GenerateResult {
  const packageJson = {
    name: slugify(profile.name) || 'generated-app',
    version: '0.1.0',
    private: true,
    type: 'module',
    description: `Generated by Spec-Ingest Tool from the "${profile.name}" profile.`,
    scripts: {
      start: 'node server.mjs',
      test: 'node --test',
    },
  }

  const files: GeneratedFile[] = [
    { path: 'package.json', content: JSON.stringify(packageJson, null, 2) + '\n' },
    { path: '.gitignore', content: 'node_modules/\n' },
    {
      path: 'README.md',
      content:
        `# ${profile.name}\n\n${classificationBanner(options.classification)}\n\n${profile.description}\n\n` +
        'Generated by Spec-Ingest Tool -- every backend route is a 501 stub naming the ' +
        'source candidate that justified it; nothing here was invented. `npm install && npm test` ' +
        'to verify; `npm start` to run.\n',
    },
    ...generateBackend(corpus),
    ...generateFrontend(corpus, profile, options),
    ...generateTests(corpus),
    ...generateCiWorkflow(),
    ...generateTerraform(profile),
  ]

  return { files }
}

export async function writeGeneratedFiles(outDir: string, files: GeneratedFile[]): Promise<void> {
  for (const file of files) {
    const fullPath = join(outDir, file.path)
    await mkdir(dirname(fullPath), { recursive: true })
    await writeFile(fullPath, file.content, 'utf-8')
  }
}
