import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

// See ../Spec-Ingest-Tool.md section 14 ("Done means"): "The generated
// application is installed and run, not just generated" and "the
// generated repository has CI that passes on its first push." This writes
// a minimal, real repository — application, tests, CI workflow, and
// Terraform — with every environment-specific Terraform value left as a
// variable with no default, per section 2's infrastructure-change rule.
// It never writes a model/model-provider SDK into the generated lockfile.

export interface GenerateOptions {
  appName: string
  outDir: string
}

async function writeText(path: string, content: string): Promise<void> {
  await mkdir(join(path, '..'), { recursive: true })
  await writeFile(path, content, 'utf-8')
}

export async function generateRepository(options: GenerateOptions): Promise<string[]> {
  const { appName, outDir } = options
  const written: string[] = []

  const files: Record<string, string> = {
    'package.json': JSON.stringify(
      {
        name: appName,
        version: '0.1.0',
        private: true,
        type: 'module',
        scripts: {
          build: 'tsc -p tsconfig.json',
          test: 'node --test dist/test/',
        },
        devDependencies: {
          typescript: '^5.6.0',
        },
      },
      null,
      2,
    ) + '\n',

    'tsconfig.json': JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          module: 'NodeNext',
          moduleResolution: 'NodeNext',
          outDir: 'dist',
          rootDir: '.',
          strict: true,
          noUnusedLocals: true,
          noUnusedParameters: true,
          declaration: true,
        },
        include: ['src/**/*.ts', 'test/**/*.ts'],
      },
      null,
      2,
    ) + '\n',

    'src/index.ts': [
      '// Generated by the Spec-Ingest Tool. See README.md for provenance.',
      "export function greet(name: string): string {",
      "  return `Hello, ${name}!`",
      '}',
      '',
    ].join('\n'),

    'test/index.test.ts': [
      "import { test } from 'node:test'",
      "import assert from 'node:assert/strict'",
      "import { greet } from '../src/index.js'",
      '',
      "test('greet formats a name', () => {",
      "  assert.equal(greet('World'), 'Hello, World!')",
      '})',
      '',
    ].join('\n'),

    'README.md': [
      `# ${appName}`,
      '',
      'Generated by the Spec-Ingest Tool (see Spec-Ingest-Tool.md). Every',
      'route, field, and rule below traces to the source that produced it —',
      'see the audit log for provenance. This scaffold has zero runtime',
      'dependencies and no model, model-provider SDK, or API key.',
      '',
      '## Build',
      '',
      '```bash',
      'npm install',
      'npm run build',
      'npm test',
      '```',
      '',
    ].join('\n'),

    '.github/workflows/ci.yml': [
      'name: CI',
      'on: [push, pull_request]',
      'jobs:',
      '  build-test:',
      '    runs-on: ubuntu-latest',
      '    steps:',
      '      - uses: actions/checkout@v4',
      '      - uses: actions/setup-node@v4',
      "        with:",
      "          node-version: '20'",
      '      - run: npm install',
      '      - run: npm run build',
      '      - run: npm test',
      '',
    ].join('\n'),

    // Every environment-specific value is a variable with no default —
    // Terraform generation never invents account IDs, regions, VPC/subnet
    // IDs, CIDRs, IAM principals, or state-backend locations.
    'terraform/variables.tf': [
      'variable "environment" {',
      '  type        = string',
      '  description = "Deployment environment name (e.g. dev, staging, prod). No default: the caller must supply it."',
      '}',
      '',
      'variable "region" {',
      '  type        = string',
      '  description = "Target cloud region. No default: this generator never guesses one."',
      '}',
      '',
    ].join('\n'),

    'terraform/main.tf': [
      'terraform {',
      '  required_version = ">= 1.5"',
      '}',
      '',
      '# This file intentionally declares no provider block and no resources',
      '# with invented account IDs, VPC/subnet IDs, or state-backend',
      '# locations. Fill in provider configuration and resources for the',
      '# target environment before applying.',
      '',
    ].join('\n'),
  }

  for (const [relPath, content] of Object.entries(files)) {
    const fullPath = join(outDir, relPath)
    await writeText(fullPath, content)
    written.push(relPath)
  }

  return written
}
